[package]
name = "rust-learn"
version = "0.1.0"
authors = ["Tushar R. Gosavi <tushargosavi@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.3.17"
mio = "0.6"
ipnetwork = "0.14.0"
serde = "1.0.88"
serde_derive = "1.0.88"
serde_json = "1.0.38"
serde_yaml = "0.8.8"
